### ISSUE TITLE
submodule with docker-registry

### ISSUE THREAD

**Issue by SydOps** [zhengxiaochuan-3/docker-image-pier#2]
This tool has nice function which I am looking for. Thanks.

Looking the code, seems you built the codes based on docker-registry (https://github.com/docker/docker-registry). But it is bad habit to copy and paste it into your repository directly. 

Git has submodule function to get updated codes from other module always. Could you update it with submodule function?

**Comment by zhengxiaochuan-3** [comment]
thanks for remind

**Comment by zhengxiaochuan-3** [comment]
thanks for remind

**Comment by SydOps** [comment]
so will you update it?

**Comment by zhengxiaochuan-3** [comment]
yes i will 



zhengxiaochuan-3@163.com
 
From: Bill W
Date: 2015-11-09 17:32
To: zhengxiaochuan-3/docker-image-pier
CC: zhengxiaochuan-3
Subject: Re: [docker-image-pier] submodule with docker-registry (#2)
so will you update it?
